### ISSUE TITLE
k8s --repos being set to an empty environment variable?

### ISSUE THREAD

**Issue by fabiobrz** [andreaTP/playing-with-jbang#2]
[k8s-shell.sh](https://github.com/andreaTP/playing-with-jbang/blob/main/k8s-shell.sh#L13) sets the `--repos`  option but there's no place where the used environment variable has been set.

I am not able to reproduce it now, but I am pretty sure I hit some kind of URL related exception because of it.

Is this wanted or should it be removed together with the following `//REPOS` directive? Or set them conditionally in case the user wants to stay "offline"?

WDYT @andreaTP ?

**Comment by andreaTP** [comment]
It's a leftover since I was using the script with `6.0.0-SNAPSHOT` removed in main now, thanks for rising it!
